import streamlit as st
from PIL import Image
import pandas as pd
import altair as alt

# Image generated by DALL-E
image = Image.open("./dna-logo.png")

st.image(image, use_column_width=True)

st.write("""
# DNA Nucleotide Count Streamlit App

This app counts the nucleotide composition of query DNA!

---
""")


st.header("Enter DNA sequence")

sequence_input = ">DNA Query 2\nGAACACGTGGAGGCAAACAGGAAGGTGAAGAAGAACTTATCCTATCAGGACGGAAGGTCCTGTGCTCGGG\nATCTTCCAGACGTCGCGACTCTAAATTGCCCCCTCTGAGGTCAAGGAACACAAGATGGTTTTGGAAATGC\nTGAACCCGATACATTATAACATCACCAGCATCGTGCCTGAAGCCATGCCTGCTGCCACCATGCCAGTCCT"
sequence = st.text_area("Sequence input", sequence_input, height=150)
sequence = sequence.splitlines()
sequence = sequence[1:]
sequence = "".join(sequence)

st.write("""
---
""")
st.header("INPUT (DNA Query)")
sequence

st.header("OUTPUT (DNA Nucleotide Count)")

st.write("Four Different ways to display output")

st.subheader("1. Dictionary")


def DNA_nucleotide_count(seq):
    return {
        "A": seq.count("A"),
        "T": seq.count("T"),
        "G": seq.count("G"),
        "C": seq.count("C"),
    }


X = DNA_nucleotide_count(sequence)

X


st.subheader("2. Text")

f"There are {X['A']} adenine (A)"
f"There are {X['T']} thymine (T)"
f"There are {X['G']} guanine (G)"
f"There are {X['C']} cytosine (C)"

st.subheader("3. DataFrame")
df = pd.DataFrame.from_dict(X, orient="index")
df.reset_index(inplace=True)
df.columns = ["nucleotide", "count"]
df

st.subheader("4. Bar chart")
chart = alt.Chart(df).mark_bar().encode(
    x="nucleotide",
    y="count"
).properties(
    width=alt.Step(80)
)
chart
